# **NUMPY LEARNING**
*~ Kathir Karthik M*

In [ ]:
import numpy as np

In [ ]:
# Creation
a = np.array([7,8,9], dtype = np.int16)
b = np.array([[3.0,7.9,6.8],[3.0,7.9,6.8]])
print(type(a))
print(a)
print(b)


<class 'numpy.ndarray'>
[7 8 9]
[[3.  7.9 6.8]
 [3.  7.9 6.8]]


In [ ]:
# Dimensions


print(a.ndim)
print(b.ndim)

c = np.array([4,5] , ndmin = 4)     # ndmin
print(c.ndim)                       # ndim

1
2
4


In [ ]:
# Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Datatype
print(a.dtype)
print(b.dtype)

int16
float64


In [ ]:
# Item size
print(a.itemsize)      # 16 bit int value so each itemsize 16/8 = 2bytes   so each item 2 byte
print(b.itemsize)      # 64 bit float value so each itemsize 64/8 = 8bytes  so each item 8 byte

2
8


In [ ]:
# no of elements
print (a.size)


# Total no of bytes
print (a.size * a.itemsize)
#    (or)
print (a.nbytes)


3
6
6


**INDEXING AND ACCESSING**

In [ ]:
# indexing, acsessing

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
print(a[0, 6])

7


In [ ]:
# Get a specific row
print(a[0, :])


[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
print(a[:, 5])


[ 6 13]


In [ ]:
# Slicing   [startindex:endindex:stepsize]
a[0 ,    1:-1:2]    # intrepreter takes as [firstelement ,last element-1,step-1 ]


array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3D arrays
d = np.array([[[3,4],[4,5]],[[6,7],[7,8]]])
print(d)

[[[3 4]
  [4 5]]

 [[6 7]
  [7 8]]]


In [ ]:
print(d[0,1,1])       #first row second element's second element
print(d[:,1,:])
d[:,1,:]=[[1,1],[1,1]]
print(d)

1
[[1 1]
 [1 1]]
[[[3 4]
  [1 1]]

 [[6 7]
  [1 1]]]


**BUILT-IN FUNCTIONS**

In [ ]:
# Filling with zeros
e=np.zeros((2,3))
print(e)

# Filling with ones
np.ones((2,3,2),dtype=np.int16)

[[0. 0. 0.]
 [0. 0. 0.]]


array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [ ]:
# filling the array with nos using full
print(np.full((2,3),7))                 # np.full (  (shape) , number )

print(np.full((2,3),[4,5,4]))

print(np.full_like(a,5))               # np.full_like( array , number)  same as np.full( array.shape, number)

print(np.full(a.shape, 5))

[[7 7 7]
 [7 7 7]]
[[4 5 4]
 [4 5 4]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


*Random function*

In [ ]:
#random array generation
print(np.random.rand(3,3))

print(np.random.randint(2,6,size=(3,3)))


[[0.1889255  0.83219214 0.91688471]
 [0.37162991 0.7160225  0.76253163]
 [0.71832229 0.08303689 0.41479835]]
[[2 2 5]
 [2 2 2]
 [5 4 3]]


*Matrix generation*

In [ ]:
print(np.identity(3,dtype=np.int16))            # identity generates a square matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
arr = np.array([1,2,3])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
arr = np.array([[1,2,3]])                         # Repeating
np.repeat(arr,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
output = np.ones((5,5),dtype=np.int16)
print(output)

r = np.zeros((3,3))
r[1,1]=9
print(r)

output[1:4,1:4] = r
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**COPYING**

In [ ]:
A = np.array([1,2,3])
B = A.copy()                        # array.copy()
B[1] =100

print(A)
print(B)

[1 2 3]
[  1 100   3]


**MATH FUNCTIONS/ AGGREGATE FUNCTIONS**

In [ ]:
r = np.array([[1,4],[2,3]])
r

array([[1, 4],
       [2, 3]])

In [ ]:
r+1                                # add each element with 1

array([[2, 5],
       [3, 4]])

In [ ]:
r-1                                # subract each element with 1

array([[0, 3],
       [1, 2]])

In [ ]:
r*2                                # multiply each element with 2

array([[2, 8],
       [4, 6]])

In [ ]:
r**2                               # squaring each item of the array

array([[ 1, 16],
       [ 4,  9]])

In [ ]:
print(np.max(r))                   # giving the biggest element in the array

4


In [ ]:
print(np.min(r))                    # giving the smallest element in the array

1


In [ ]:
s = np.array([[1,4],[2,-3]])        # comparing and giving the maximum of two arrays
print(np.maximum(r,s))

[[1 4]
 [2 3]]


In [ ]:
np.sin(r)

array([[ 0.84147098, -0.7568025 ],
       [ 0.90929743,  0.14112001]])

In [ ]:
np.cos(r)

array([[ 0.54030231, -0.65364362],
       [-0.41614684, -0.9899925 ]])

In [ ]:
np.tan(r)

array([[ 1.55740772,  1.15782128],
       [-2.18503986, -0.14254654]])

**STAISTICS**

In [ ]:
np.mean(r)

2.5

In [ ]:
np.median(r)

2.5

In [ ]:
np.average(r)

2.5

In [ ]:
np.sum(r,axis =1)

array([5, 5])

**LINEAR ALGEBRA**

In [ ]:
u = np.ones((3,2))
print(u)
v = np.full((2,3),2)
print(v)

print(np.matmul(u,v))          # can be done only when two matrix is  a x b   b x a   form  no of columns = no of rows

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [ ]:
u = np.identity(3 , dtype = np.int16)
print(np.linalg.det(u))

1.0


**RE-ORGANIZING ARRAYS**

In [ ]:
# Reshaping the arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([2,3,5,6])
print(np.vstack([v1,v2]))



[[1 2 3 4]
 [2 3 5 6]]


In [ ]:
# horizontal stacking
print(np.hstack((v1,v2)))


a1 = np.ones((2,3))
a2 = np.zeros((2,2))

print(np.hstack((a1,a2)))

[1 2 3 4 2 3 5 6]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


 **FETCHING FILE DATA HANDLING**

In [ ]:
# getting data from a file without using PANDAS
filedata = np.genfromtxt('data.txt', delimiter=',',dtype = np.int16)
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [ ]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])